#!/bin/bash -e

# These includes are unnecessary from a preprocessor perspective but are required
# as pointers to the Arduino IDE as to which additional libraries to include.
cat > ble_stream_echo.ino << EOF
#include <SPI.h>
#include <lib_aci.h>
#include <BleCore.h>

EOF

cat ble_stream_echo.cpp >> ble_stream_echo.ino
